<div class="storelanguage-canvas" style="background:#f2f2f2; color:#777;">
<div class="container" style="text-align:right;">
<style>
@media only screen and (max-width: 767px){
  .storelanguage-canvas{display:none}}
</style>
<div class="switcher store switcher-storelanguage" id="switcher-storelanguage">
    <strong class="label switcher-label"><span>Language</span></strong>
    <div class="actions dropdown options switcher-options">
               <div class="action toggle switcher-trigger" role="button" tabindex="0" data-toggle="dropdown" data-trigger-keypress-button="true" id="switcher-storelanguage-trigger" aria-haspopup="true" aria-expanded="false">
                <strong>
                    <span>Language</span>
                </strong>
            </div>
                        <ul class="dropdown switcherdropdown" id="storelanguage-ul" data-target="dropdown" aria-hidden="true" style="min-width: 80px;">
                                <li class="switcher-option"> <a href="/" >English</a> </li>
                                <li class="switcher-option"> <a href="/japan/" >日本語</a> </li>
                        </ul>
    </div>
</div>
 
 
</div>
</div>
<script>
var switcherStorelanguage = document.getElementById("switcher-storelanguage")
    var storelanguageUl = document.getElementById("storelanguage-ul")
    switcherStorelanguage.onclick = function(){
      if(storelanguageUl.className=='dropdown switcherdropdown'){
        storelanguageUl.className="dropdown switcherdropdown active"
        storelanguageUl.style.display="block"
      }else{
        storelanguageUl.className="dropdown switcherdropdown"
        storelanguageUl.style.display="none"
      }
    }
</script>
